### ISSUE TITLE
Scheduler period_ms parameter ignored

### ISSUE THREAD

**Issue by dtcray** [cea-hpc/robinhood#102]
Robinhood config read seem to ignore period_ms option and always set this to 1000ms (default).
there seem to be a parameter inconsistency in sched_ratelimit.c lines 235-239.
lines 235 uses "period_ms" (allowed parameters)
line 239 uses "period" (tbf_params)

**Comment by tl-cea** [comment]
Thank you for pointing this out.
This explains some incorrect rate limitations i've seen.

**Comment by tl-cea** [comment]
Thank you for the fix https://review.gerrithub.io/c/cea-hpc/robinhood/+/437807
It looks good.
Sorry for the integration delay. The test/validation platform is currently under heavy reconstruction. It will take some time to get it back.

**Comment by tl-cea** [comment]
Fixed in 3.1.5
