### ISSUE TITLE
Lustre 2.12 support

### ISSUE THREAD

**Issue by thiell** [cea-hpc/robinhood#103]
Hey!

We now have systems running Lustre 2.12 LTS but Robinhood is not compatible with DoM nor PFL yet. We use both features, so robinhood keeps saying that:

2019/01/24 23:51:42 [80692/15] GetStripe | Unsupported Luster magic number from getstripe: 0XBD60BD0

Is there a way to disable OST stripping info in the config as of 3.1.4? It's generating a lot of logs. Thanks!!

**Comment by tl-cea** [comment]
Fixed in 3.1.5
Thomas
