### ISSUE TITLE
Initialize changelog record ID

### ISSUE THREAD

**Issue by degremont** [cea-hpc/robinhood#11]
When using several several changelog readers with a Lustre MDT, if the most recent one (ie: cl2) is given to Robinhood, it will process the oldest records, whatever cl2 is currently pointing to.
There should be a way to tell to RBH : only process records starting from where cl2 currently is.

**Comment by tl-cea** [comment]
It was fixed since a while. And this mecanism has been enhanced by commit 801b312.
