### ISSUE TITLE
./configure missing, autogen.sh fails

### ISSUE THREAD

**Issue by matthiasbeyer** [cea-hpc/robinhood#112]
The release tarball does not contain a `configure` script as claimed by your installation documentation and the `autogen.sh` script fails:

```
configure.ac:79: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

**Comment by qb-cea** [comment]
The error message makes me think you are missing the `libtool` package.
But even then, `autogen.sh` is likely to fail when run from a release tarball as it assumes it is run from inside a git repository.

After installing `libtool`, the easiest way to generate a `configure` script and build the project is to use the standard autotools procedure:

```console
$ autoreconf --install && ./configure && make -j $(nproc)
```

**Comment by matthiasbeyer** [comment]
Does not work:

```
+ autoreconf -i -f
configure.ac:79: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

libtool is installed.

**Comment by martinetd** [comment]
That error really shouldn't happen with libtool installed.

`AC_PROG_LIBTOOL` is defined in `/usr/share/aclocal/libtool.m4` which is in the libtool package in most distros;
what distribution are you using and can you check this file appears ok? (`rpm -qf /usr/share/aclocal/libtool.m4` should list libtool and `rpm -V libtool` should be empty on rhel-based distro)



That being said we should regenerate a release tarball after autogen setup as that is the standard way of distribution.

**Comment by tl-cea** [comment]
The distribution tarball does contain a configure script:
```
$ tar ztvf robinhood-3.1.5.tar.gz | grep configure
-rwxr-xr--  605224 2019-03-20 13:23 robinhood-3.1.5/configure
```
