### ISSUE TITLE
robinhood 3.1.5.1 ChangeLog | Error in llapi_changelog_recv(): -2: No such file or directory

### ISSUE THREAD

**Issue by yoyz** [cea-hpc/robinhood#116]
Hi robinhood developper !

We have an issue at one site.
Sometime we have the following line which appear in robinhood : 
2021/01/07 17:07:19 [126887/2] ChangeLog | Error in llapi_changelog_recv(): -2: No such file or directory
2021/01/07 17:07:20 [126887/2] ChangeLog | Error in llapi_changelog_recv(): -2: No such file or directory
2021/01/07 17:07:21 [126887/2] ChangeLog | Error in llapi_changelog_recv(): -2: No such file or directory
2021/01/07 17:07:22 [126887/2] ChangeLog | Error in llapi_changelog_recv(): -2: No such file or directory
2021/01/07 17:07:23 [126887/2] ChangeLog | Error in llapi_changelog_recv(): -2: No such file or directory
2021/01/07 17:07:24 [126887/2] ChangeLog | Error in llapi_changelog_recv(): -2: No such file or directory

When this happen the changelog reader of this MDT which is in our case MDT0003 stop reading new changelog entry.
Restarting the service solve the issue, and the new entry are ingest by robinhood.
So there is some kind of issue which make robinhood not able anymore to read entry, and it's difficult to know the reason behind that.

Lustre server run 2.12.3 as robinhood server.
I can add the server configuration if you need it, but basically robinhood works fine until we see this issue which happen around once a month.

**Comment by ypsah** [comment]
I think you are looking for [this commit](https://github.com/cea-hpc/robinhood/commit/997eeba0586e3a3f2119c8a7425004665d4ebc08).

@tl-cea maybe you should release 3.1.6

**Comment by yoyz** [comment]
Thanks a lot ypsah ! 
This look to be exactly what i'm looking for.
So just need the next release looking at git log :+1:

**Comment by ypsah** [comment]
Just to be clear, ypsah is the new handle I use (formerly qb-cea), I messed up a little, so I started using a separate account, then realised that meant I would lose my current permissions, and ended up just renaming my current account.

Long story short: when yoyz wrote "ypsah" in their comment above, they were right to do so.

**Comment by tl-cea** [comment]
Hello,

> @tl-cea maybe you should release 3.1.6

It was released on 2020/09/29.

Thomas

De : ypsah [mailto:notifications@github.com]
Envoyé : vendredi 8 janvier 2021 16:38
À : cea-hpc/robinhood
Cc : LEIBOVICI Thomas 601315; Mention
Objet : Re: [cea-hpc/robinhood] robinhood 3.1.5.1 ChangeLog | Error in llapi_changelog_recv(): -2: No such file or directory (#116)


I think you are looking for this commit<https://github.com/cea-hpc/robinhood/commit/997eeba0586e3a3f2119c8a7425004665d4ebc08>.

@tl-cea<https://github.com/tl-cea> maybe you should release 3.1.6

**Comment by yoyz** [comment]
Hi Thomas, 

Sorry looking at the tag in github, I have not seen that the version was yet available.
Thanks a lot !

**Comment by tl-cea** [comment]
Sorry, my mistake.
It looks I missed pushing the tag.
Fixed.

De : yoyz [mailto:notifications@github.com]
Envoyé : vendredi 8 janvier 2021 18:26
À : cea-hpc/robinhood
Cc : LEIBOVICI Thomas 601315; State change
Objet : Re: [cea-hpc/robinhood] robinhood 3.1.5.1 ChangeLog | Error in llapi_changelog_recv(): -2: No such file or directory (#116)


Hi Thomas,

Sorry looking at the tag in github, I have not seen that the version was yet available.
Thanks a lot !
