### ISSUE TITLE
rbh-report: volume Buggy output?

### ISSUE THREAD

**Issue by ahkumar** [cea-hpc/robinhood#118]
Hi Robinhood Team,

I see this odd output. Can anybody please help me understand this? I see the volume showing in PB usage while the space used is only 13.67 TB. Is this some kind of bug? I am using version 3.1.6;

#rbh-report --topusers 
rank,       user,     volume,   spc_used,      count,   avg_size
   1,  username,  181.01 PB,   13.66 TB,    3801758,   49.93 GB

# rbh-report -u username
      user,     type,      count,     volume,   spc_used,   avg_size
 username,  symlink,      15457,    1.13 MB,  188.68 MB,         77
 username,      dir,     202312,    6.68 GB,    6.68 GB,   34.60 KB
 username,     file,    3801758,  181.01 PB,   13.66 TB,   49.93 GB

Total: 4019527 entries, volume: 203804321727422287 bytes (181.01 PB), space used: 15029954365952 bytes (13.67 TB)

Thank you,
Amit

**Comment by tl-cea** [comment]
Hello,
As replied on the mailing list, you may have sparse files, or released files if you use the Lustre HSM feature.

**Comment by ahkumar** [comment]
Thank you!! And sorry lost track of this with other things going on.
