### ISSUE TITLE
webgui: any page listed in routes.xml is 404

### ISSUE THREAD

**Issue by caljess599** [cea-hpc/robinhood#14]
I have the webgui up and running but am unable to load any content that depends on the virtual urls as described in app/config/routes.xml. This means that the links to users, groups, sizes, and search and that I also get blank white box popup when I try to see more details about a user.
I have read what I could find about other people having this same issue and yet none of the fixes I have read about have resolved this problem. 

* The prereqs are installed 
* From our apache conf
```
<Directory /<path/to/php/>
        AllowOverride All
</Directory>
```
* apache owns the files it needs to read/write

Any assistance with this issue would be most appreciated!

**Comment by tl-cea** [comment]
Just now be fixed with just released 3.0 (final).
