### ISSUE TITLE
Can't exclude sorting in rmdir module

### ISSUE THREAD

**Issue by Elwell** [cea-hpc/robinhood#15]
Can this be implemented in the same way as purge?

resmon_purge.c:    sort_type.order = (resmon_config.sort ? SORT_ASC : SORT_NONE);

but there's a hard-coded 
rmdir_main.c:    sort_type.attr_index = ATTR_INDEX_last_mod;
rmdir_main.c:    sort_type.order = SORT_ASC;
(twice) in the source for rmdir. Is this necessary?

**Comment by tl-cea** [comment]
This is fixed in v3. All policies implement the same parameters.
