### ISSUE TITLE
web inteface doesnot work with mysql 5.7.12

### ISSUE THREAD

**Issue by arm2arm** [cea-hpc/robinhood#19]
I have following setup:
mysql 5.7.12 community edition
robinhood 2.5.5(or 3.0.0 alpha )

The web interface shows following error after setup:

Error: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'rbh_llust.ACCT_STAT.gr_name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

    Volume
    Count
    List

**Comment by ja-cea** [comment]
Hello, 

Could you try with #23, it should solve the issue

**Comment by arm2arm** [comment]
Looks nice, but now somehow routes are not working for left side menu:
http://l2.cls/robinhood/users.php is not redirected to right site, gives 404
but this http://l2.cls/robinhood/ works as expected

**Comment by tl-cea** [comment]
Web UI is being fully rewritten. The new version will be available with rbh 3.0-rc2.

**Comment by tl-cea** [comment]
Just now be fixed with just released 3.0 (final).
