### ISSUE TITLE
Avoiding RPM build error: canonicalization unexpectedly shrank by one character

### ISSUE THREAD

**Issue by thiell** [cea-hpc/robinhood#20]
I just hit a strange issue when compiling the latest b_3.0 against Lustre.

This works well:
```
$ ./configure --with-lustre=$HOME/lustre-release_2_5
```

but this doesn't:
```
./configure --with-lustre=$HOME/lustre-release_2_5/
...
extracting debug info from /tmp/robinhood/rpms/BUILDROOT/robinhood-3.0-0.alpha2.lustre2.5.el6.x86_64/usr/lib64/robinhood/librbh_mod_backup.so.0.0.0
/usr/lib/rpm/debugedit: canonicalization unexpectedly shrank by one character
error: Bad exit status from /var/tmp/rpm-tmp.UNuUsa (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.UNuUsa (%install)
make: *** [rpms] Error 1
```

Did you notice the difference? It's the / at the end of the lustre path. I wanted to share this as it took me some time to find out... I don't know if that's easily fixable.

**Comment by tl-cea** [comment]
This ./configure option is mainly used for particular packaging of some software vendors (rarely by common users as they have lustre installed on their build box).
If you really need it, it shouldn't be hard to fix, and your contribution is welcome.

**Comment by thiell** [comment]
If you want to laugh a little bit, I found a redhat ticket created in 2007 and still open about that issue... :)

https://bugzilla.redhat.com/show_bug.cgi?id=304121

And I tried to reproduce the issue tonight but can't anymore!! I close this ticket.
