### ISSUE TITLE
ListMgr error messages with value is out of range / DB_REQUEST_FAILED

### ISSUE THREAD

**Issue by thiell** [cea-hpc/robinhood#21]
Hi,

With v3 alpha2, restarted robinhood with --readlog after a few hours downtime and got a bunch of error messages:

Note: I use mysql-community-server-5.6.30-2.el6.x86_64

2016/05/06 00:32:17 [9784/14] EntryProc | Error 7 performing database operation: request error.
2016/05/06 00:32:17 [9784/5] ListMgr | Unhandled error 1690: default conversion to DB_REQUEST_FAILED
2016/05/06 00:32:17 [9784/5] ListMgr | Error 7 executing query 'UPDATE ENTRIES SET nlink=nlink-1 WHERE id='0x200023cab:0x15b97:0x0'': BIGINT UNSIGNED value is out of range in '(`robinhood_regal`.`ENTRIES`.`nlink` - 1)'
2016/05/06 00:32:17 [9784/5] EntryProc | Error 7 performing database operation: request error.
2016/05/06 00:32:17 [9784/31] ListMgr | Unhandled error 1690: default conversion to DB_REQUEST_FAILED
2016/05/06 00:32:17 [9784/31] ListMgr | Error 7 executing query 'UPDATE ENTRIES SET nlink=nlink-1 WHERE id='0x200023cab:0x15b98:0x0'': BIGINT UNSIGNED value is out of range in '(`robinhood_regal`.`ENTRIES`.`nlink` - 1)'

**Comment by tl-cea** [comment]
Proposed fix:
    https://review.gerrithub.io/#/c/275856/

**Comment by tl-cea** [comment]
Fix landed
