### ISSUE TITLE
Non-default rules fail to execute

### ISSUE THREAD

**Issue by cfaber** [cea-hpc/robinhood#25]
In 3.0, (2.99, etc). It appears that non-default rules within policies fail to execute. This may be related to the full file system scan not completing issues posted here, however as it stands now, the latest pull (as of last night) no rules within a policy (periodic or otherwise) appear to execute at all. That said, default rules do execute, however file class rules are explicitly disallowed.

**Comment by tl-cea** [comment]
You're welcome to reopen if it still fails in final 3.0.
