### ISSUE TITLE
Tests fail with latest build

### ISSUE THREAD

**Issue by cfaber** [cea-hpc/robinhood#26]
As of today's pull / build of master, and RPM installs tests fail:

==== TEST #100 info_collect.conf (escape string in SQL requests) ====
Test start: 2016-06-07 07:51:15.164933458
1-Reading changelogs...
2016/06/07 07:51:16 [57382/1] mod_mgt | Cannot dlopen() 'librbh_mod_common.so': librbh_mod_common.so: cannot open shared object file: No such file or directory
Error reading configuration file '/usr/share/robinhood/tests/test_suite/cfg/info_collect.conf': Error 22 reading policies configuration:
default_action: unknown function 'common.unlink'
ERROR 
grep: *.log: No such file or directory
grep: rh_chglogs.log: No such file or directory
grep: rh_chglogs.log: No such file or directory
grep: rh_chglogs.log: No such file or directory
grep: rh_chglogs.log: No such file or directory
grep: rh_chglogs.log: No such file or directory
warning: 0 close record (lustre version 2.8.0), 4 expected
./2-run-tests.sh: line 8270: bc: command not found
Test end: 2016-06-07 07:51:17.272810400
duration:  sec
Filesystem cleanup...

**Comment by cfaber** [comment]
Sorry, ignore the issue with bc, tests still fail with it present.

**Comment by cfaber** [comment]
So RPM fails to add /usr/lib64/robinhood to the linker paths.

**Comment by cfaber** [comment]
additionally your clean.sh script doesn't account for rh.log which grows significantly.

**Comment by tl-cea** [comment]
We did not test robinhood on Lustre 2.8 yet. So you feedback is greatly welcome :)

Robinhood test_suite was originally written to run in robinhood build/source tree. Cray recently packaged it as a RPM, but it seems - according to your reports - that there is some lacks in this RPM.

Here is the way to we commonly run tests:
https://github.com/cea-hpc/robinhood/wiki/Contributing#testing-your-patch

As of today, testing with LUSTRE/HSM + Lustre 2.7, only test 115 and 226a should fail (for known reasons).

**Comment by fzago-cray** [comment]
On CentOS 6, the robinhood-lustre-3.0-0 rpms installs /etc/ld.so.conf.d/robinhood.conf, which contains

    /usr/lib64/robinhood/

and then it runs ldconfig. 

What is your OS? Is the above file present, and is the content correct?

**Comment by cfaber** [comment]
Centos 7 minimal

**Comment by fzago-cray** [comment]
And the other question?

**Comment by cfaber** [comment]
Apologies for my terse response. The file is present, however it points to
the incorrect lib path: /usr/lib64/robinhood vs the install path at
/lib64/robinhood

(hardcoded?)

**Comment by fzago-cray** [comment]
On my centos 7 install, /lib64 is a symlink to /usr/lib64, so that shouoldn't matter.

How did you configure robinhood?

**Comment by cfaber** [comment]
./autogen.sh
./configure
make rpms
rpm -ql | grep robinhood | xargs rpm -r
rpm -ivh rpms/RPMS/x86_64/robinhood-*.rpm


and hm.. interesting, I hadn't taken that close of look but yes, it does
default, however ldconfig doesn't seem to pick up the libraries. Not sure
why. The problem was pretty easily reproduced on a fresh, minimal install.

Today I'll put together another minimal image, rebuild, and test to see if
this still happens.

I don't recall if I manually ran ldconfig -r before sticking the robinhood
/lib64/robinhood path in.

-cf

**Comment by fzago-cray** [comment]
If you run

    rpm -qlp rpms/RPMS/x86_64/robinhood-lustre-3.0-0.alpha2.lustre2.7.el6.x86_64.rpm

(or whatever the rpm is called on your machine), are the libraries installed in /usr/lib64?

    /usr/lib64/robinhood/librbh_mod_alerter.so
    /usr/lib64/robinhood/librbh_mod_alerter.so.0
    /usr/lib64/robinhood/librbh_mod_alerter.so.0.0.0
    /usr/lib64/robinhood/librbh_mod_backup.so
    /usr/lib64/robinhood/librbh_mod_backup.so.0
    /usr/lib64/robinhood/librbh_mod_backup.so.0.0.0
    /usr/lib64/robinhood/librbh_mod_checker.so
    /usr/lib64/robinhood/librbh_mod_checker.so.0
    /usr/lib64/robinhood/librbh_mod_checker.so.0.0.0
    /usr/lib64/robinhood/librbh_mod_common.so
    /usr/lib64/robinhood/librbh_mod_common.so.0
    /usr/lib64/robinhood/librbh_mod_common.so.0.0.0
    /usr/lib64/robinhood/librbh_mod_lhsm.so
    /usr/lib64/robinhood/librbh_mod_lhsm.so.0
    /usr/lib64/robinhood/librbh_mod_lhsm.so.0.0.0

**Comment by tl-cea** [comment]
On EL6, library loading paths are refreshed when /sbin/ldconfig is called.
Looking at the spec file, it seams it is not called in the "%if %{with_systemd}" block (on el7).

**Comment by tl-cea** [comment]
Fix:
https://review.gerrithub.io/#/c/280714/

**Comment by tl-cea** [comment]
Colin, can you please confirm this is fixed by latest version, so we can close this ticket?

**Comment by tl-cea** [comment]
All fixes landed.
