### ISSUE TITLE
Test 508 failure

### ISSUE THREAD

**Issue by cfaber** [cea-hpc/robinhood#30]
In this case this test was erroneously skipped, MariaDB is installed and available on this system.

==== TEST #508 Test TokuDB compression (Test TokuDB compression) ====
Test start: 2016-06-07 12:07:19.081697757
package MariaDB-common is not installed
MariaDB not installed: skipped
Test end: 2016-06-07 12:07:19.565682062
duration: .471151366 sec
Filesystem cleanup...

**Comment by tl-cea** [comment]
You're welcome to reopen if it still fails in final 3.0.
