### ISSUE TITLE
Test 613n failure

### ISSUE THREAD

**Issue by cfaber** [cea-hpc/robinhood#32]
==== TEST #613n PurgeClass_ExtendedAttribut.conf (TEST_PURGE_CLASS_EXTENDED_ATTRIBUT) ====
Test start: 2016-06-07 12:24:47.216789693
Create Files ...
setfattr: /mnt/lustre/dir1/file.4: Operation not supported
setfattr: /mnt/lustre/dir1/file.5: Operation not supported
Scan and apply purge policy (--run=purge --target=all)...
ERROR ********** TEST FAILED (Log): 0 files purged, but 1 expected
rh_purge.log:2016/06/07 12:24:48 [41348/1] Main | FS Scan module successfully initialized
rh_purge.log:2016/06/07 12:24:48 [41348/3] FS_Scan | Launching FS Scan starter thread
rh_purge.log:2016/06/07 12:24:48 [41348/4] Main | Statistics thread started
rh_purge.log:2016/06/07 12:24:48 [41348/3] FS_Scan | Starting scan of /mnt/lustre
rh_purge.log:2016/06/07 12:24:48 [41348/3] FS_Scan | 12 entries in DB before starting the scan
rh_purge.log:2016/06/07 12:24:48 [41348/5] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/5] Policy | [0x2000013a5:0xa115:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/6] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/6] Policy | [0x2000013a5:0xa10f:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/7] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/7] Policy | [0x2000013a5:0xa114:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/6] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/6] Policy | [0x2000013a5:0xa10e:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/8] FS_Scan | openat failed on <parent_fd=6>/link.2: Too many levels of symbolic links
rh_purge.log:2016/06/07 12:24:48 [41348/8] FS_Scan | openat failed on <parent_fd=6>/link.1: Too many levels of symbolic links
rh_purge.log:2016/06/07 12:24:48 [41348/9] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/9] Policy | [0x2000013a5:0xa116:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/10] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/10] Policy | [0x2000013a5:0xa10c:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/11] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/11] Policy | [0x2000013a5:0xa110:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/9] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/9] Policy | [0x2000013a5:0xa10d:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/8] FS_Scan | Flushing pipeline...
rh_purge.log:2016/06/07 12:24:48 [41348/12] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/12] Policy | [0x2000013a5:0xa10b:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/13] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/13] Policy | [0x2000013a5:0xa111:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/9] ListMgr | Direct deletion in NAMES table
--
rh_purge.log:2016/06/07 12:24:48 [41348/1] STATS | DB ops: get=2/ins=0/upd=12/rm=0
rh_purge.log:2016/06/07 12:24:48 [41348/1] Main | Policy purge successfully initialized
rh_purge.log:2016/06/07 12:24:48 [41348/16] purge | Checking policy rules for all
rh_purge.log:2016/06/07 12:24:48 [41348/16] purge | Building policy list - last full FS Scan: 2016/06/07 12:24:48
rh_purge.log:2016/06/07 12:24:48 [41348/16] purge | Starting policy run
rh_purge.log:2016/06/07 12:24:48 [41348/17] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/17] Policy | Error while checking if entry [0x2000013a5:0xa10d:0x0] matches file class 'test_attr' (in policy 'purge_test_attr')
rh_purge.log:2016/06/07 12:24:48 [41348/17] purge | Entry /mnt/lustre/dir1/file.1 doesn't match condition for policy rule 'default'
rh_purge.log:2016/06/07 12:24:48 [41348/17] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/17] Policy | [0x2000013a5:0xa10d:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | Error while checking if entry [0x2000013a5:0xa115:0x0] matches file class 'test_attr' (in policy 'purge_test_attr')
rh_purge.log:2016/06/07 12:24:48 [41348/18] purge | Entry /mnt/lustre/dir2/file.7 doesn't match condition for policy rule 'default'
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | [0x2000013a5:0xa115:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/19] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/19] Policy | Error while checking if entry [0x2000013a5:0xa114:0x0] matches file class 'test_attr' (in policy 'purge_test_attr')
rh_purge.log:2016/06/07 12:24:48 [41348/19] purge | Entry /mnt/lustre/dir2/file.6 doesn't match condition for policy rule 'default'
rh_purge.log:2016/06/07 12:24:48 [41348/19] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/19] Policy | [0x2000013a5:0xa114:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/20] purge | Entry /mnt/lustre/dir1/link.2 doesn't match condition for policy rule 'default'
rh_purge.log:2016/06/07 12:24:48 [41348/17] purge | Entry /mnt/lustre/dir1/link.1 doesn't match condition for policy rule 'default'
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | Error while checking if entry [0x2000013a5:0xa111:0x0] matches file class 'test_attr' (in policy 'purge_test_attr')
rh_purge.log:2016/06/07 12:24:48 [41348/18] purge | Entry /mnt/lustre/dir1/file.5 doesn't match condition for policy rule 'default'
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | [0x2000013a5:0xa111:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/19] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/19] Policy | Error while checking if entry [0x2000013a5:0xa110:0x0] matches file class 'test_attr' (in policy 'purge_test_attr')
rh_purge.log:2016/06/07 12:24:48 [41348/19] purge | Entry /mnt/lustre/dir1/file.4 doesn't match condition for policy rule 'default'
rh_purge.log:2016/06/07 12:24:48 [41348/19] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/19] Policy | [0x2000013a5:0xa110:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/20] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/20] Policy | Error while checking if entry [0x2000013a5:0xa10f:0x0] matches file class 'test_attr' (in policy 'purge_test_attr')
rh_purge.log:2016/06/07 12:24:48 [41348/20] purge | Entry /mnt/lustre/dir1/file.3 doesn't match condition for policy rule 'default'
rh_purge.log:2016/06/07 12:24:48 [41348/20] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/20] Policy | [0x2000013a5:0xa10f:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | Error while checking if entry [0x2000013a5:0xa10e:0x0] matches file class 'test_attr' (in policy 'purge_test_attr')
rh_purge.log:2016/06/07 12:24:48 [41348/18] purge | Entry /mnt/lustre/dir1/file.2 doesn't match condition for policy rule 'default'
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/18] Policy | [0x2000013a5:0xa10e:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:48 [41348/16] purge | Waiting for the end of current pass: still 4 entries pending (1 in queue, 3 being processed). Last action 0s ago.
rh_purge.log:2016/06/07 12:24:48 [41348/17] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/17] Policy | Error while checking if entry [0x2000013a5:0xa116:0x0] matches file class 'test_attr' (in policy 'purge_test_attr')
rh_purge.log:2016/06/07 12:24:48 [41348/17] purge | Entry /mnt/lustre/dir2/file.8 doesn't match condition for policy rule 'default'
rh_purge.log:2016/06/07 12:24:48 [41348/17] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_purge.log:2016/06/07 12:24:48 [41348/17] Policy | [0x2000013a5:0xa116:0x0]: an error occured when checking fileset 'test_attr'
rh_purge.log:2016/06/07 12:24:49 [41348/16] purge | End of current pass
--
rh_scan.log:2016/06/07 12:24:48 [41315/1] Main | FS Scan module successfully initialized
rh_scan.log:2016/06/07 12:24:48 [41315/3] FS_Scan | Launching FS Scan starter thread
rh_scan.log:2016/06/07 12:24:48 [41315/4] Main | Statistics thread started
rh_scan.log:2016/06/07 12:24:48 [41315/3] FS_Scan | Starting scan of /mnt/lustre
rh_scan.log:2016/06/07 12:24:48 [41315/3] FS_Scan | Notice: this is the first scan (DB is empty)
rh_scan.log:2016/06/07 12:24:48 [41315/5] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_scan.log:2016/06/07 12:24:48 [41315/5] Policy | [0x2000013a5:0xa115:0x0]: an error occured when checking fileset 'test_attr'
rh_scan.log:2016/06/07 12:24:48 [41315/6] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_scan.log:2016/06/07 12:24:48 [41315/6] Policy | [0x2000013a5:0xa10f:0x0]: an error occured when checking fileset 'test_attr'
rh_scan.log:2016/06/07 12:24:48 [41315/7] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_scan.log:2016/06/07 12:24:48 [41315/7] Policy | [0x2000013a5:0xa10e:0x0]: an error occured when checking fileset 'test_attr'
rh_scan.log:2016/06/07 12:24:48 [41315/8] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_scan.log:2016/06/07 12:24:48 [41315/8] Policy | [0x2000013a5:0xa114:0x0]: an error occured when checking fileset 'test_attr'
rh_scan.log:2016/06/07 12:24:48 [41315/9] FS_Scan | openat failed on <parent_fd=6>/link.2: Too many levels of symbolic links
rh_scan.log:2016/06/07 12:24:48 [41315/9] FS_Scan | openat failed on <parent_fd=6>/link.1: Too many levels of symbolic links
rh_scan.log:2016/06/07 12:24:48 [41315/10] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_scan.log:2016/06/07 12:24:48 [41315/10] Policy | [0x2000013a5:0xa116:0x0]: an error occured when checking fileset 'test_attr'
rh_scan.log:2016/06/07 12:24:48 [41315/11] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_scan.log:2016/06/07 12:24:48 [41315/11] Policy | [0x2000013a5:0xa10c:0x0]: an error occured when checking fileset 'test_attr'
rh_scan.log:2016/06/07 12:24:48 [41315/7] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_scan.log:2016/06/07 12:24:48 [41315/7] Policy | [0x2000013a5:0xa110:0x0]: an error occured when checking fileset 'test_attr'
rh_scan.log:2016/06/07 12:24:48 [41315/6] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_scan.log:2016/06/07 12:24:48 [41315/6] Policy | [0x2000013a5:0xa10d:0x0]: an error occured when checking fileset 'test_attr'
rh_scan.log:2016/06/07 12:24:48 [41315/12] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_scan.log:2016/06/07 12:24:48 [41315/12] Policy | [0x2000013a5:0xa111:0x0]: an error occured when checking fileset 'test_attr'
rh_scan.log:2016/06/07 12:24:48 [41315/9] FS_Scan | Flushing pipeline...
rh_scan.log:2016/06/07 12:24:48 [41315/6] Policy | Error: condition on extended attribute whereas this feature is not supported by the filesystem, or xattr name 'user.foo' is invalid)
rh_scan.log:2016/06/07 12:24:48 [41315/6] Policy | [0x2000013a5:0xa10b:0x0]: an error occured when checking fileset 'test_attr'
rh_scan.log:2016/06/07 12:24:48 [41315/6] FS_Scan | Callback from database for operation 'End of flush'
ERROR ********** TEST FAILED **********
Test end: 2016-06-07 12:24:49.774211981
duration: 2.553182357 sec
Filesystem cleanup...

**Comment by tl-cea** [comment]
Guess: lustre used to be mounted with xattr option enabled before 2.8, but it is no longer the case?

**Comment by tl-cea** [comment]
You're welcome to reopen if it still fails in final 3.0.
