### ISSUE TITLE
make rpm failing on SL 7.2 with Lustre 2.8.0, RobinH 3.0

### ISSUE THREAD

**Issue by FayeG** [cea-hpc/robinhood#33]
make rpm give this error:
error: line 29: Tag takes single token only: Release: 0.alpha1.lustrepackage lustre is not installed.el7

Here is my package lustre packages list:

rpm -qa | grep -i lustre
lustre-client-modules-2.8.0-3.10.0_327.3.1.el7.x86_64.x86_64
lustre-client-2.8.0-3.10.0_327.3.1.el7.x86_64.x86_64

The configure setup was: ./configure --prefix=/opt/robinhood --enable-lustre

**Comment by tl-cea** [comment]
Thanks for reporting.
"0.alpha1.lustrepackage lustre is not installed.el7"
It looks there is an issue with lustre detection.
Will take a look at that.

**Comment by FayeG** [comment]
I've just tried rh rc1 and it's working fine now.
Thanks you very much for looking into this.

**Comment by tl-cea** [comment]
I'm glad it solved your issue.
