### ISSUE TITLE
Add --enable-dist configure mode

### ISSUE THREAD

**Issue by mboes** [cea-hpc/robinhood#34]
There is currently a bootstrap problem when installing robinhood from git: in order to create an RPM, one needs a source RPM, but for that we need a `.spec` file, but for that we need to run `./configure` first, but this will only succeed if a number of runtime dependencies for robinhood are installed on the host first.

Ideally, we wouldn't need to install anything on the host. It should be possible to obtain a .spec file and a source distribution without running all the configure checks. This is what Lustre 2.8 does. It features a special `--enable-dist` flag, which is very handy to solve the aforementioned bootstrapping problem.

This is a feature request for adding the very same functionality to robinhood's ./configure script.

**Comment by tl-cea** [comment]
OK, I understand your problem.  Thanks for your pull request. We will test it.

**Comment by tl-cea** [comment]
Your patch is under review here:
https://review.gerrithub.io/#/c/290758/

**Comment by tl-cea** [comment]
Fix landed to git.
