### ISSUE TITLE
MySQL service name 'mysqld' causes create_db script to fail

### ISSUE THREAD

**Issue by caljess599** [cea-hpc/robinhood#35]
We use the percona packaging of mysql so (on RHEL 6.8 anyway) our service is called simply mysql, not mysqld. I had to edit the rbh-config script so it would 'OK' the service being mysql. Otherwise install of v3 went very well!

**Comment by tl-cea** [comment]
Thanks for reporting. We'll try to find a pretty manner to support both service names.

**Comment by tl-cea** [comment]
Fix has been landed to git. Will be released in incoming rc2.
