### ISSUE TITLE
3.0.0-rc1 systemd startup @script points to missing robinhood binary

### ISSUE THREAD

**Issue by FayeG** [cea-hpc/robinhood#37]
Hi,
I created rpms from 3.0.0-rc1. 
It puts the "robinhood" binary in **/opt/robinhood/sbin/robinhood** viz:
0 edi-test-ltr-03:robinhood.d# rpm -qf /opt/robinhood/sbin/robinhood
robinhood-lustre-3.0-0.rc1.lustre2.8.el7.x86_64
0 edi-test-ltr-03:robinhood.d#

But the /usr/lib/systemd/system/robinhood@.service is looking for the robinhood binary in /usr/sbin/robinhood which doesn't exist so the service fails to start on RHEL 7, viz:

0 edi-test-ltr-03:robinhood.d# rpm -qf /usr/lib/systemd/system/robinhood@.service
robinhood-lustre-3.0-0.rc1.lustre2.8.el7.x86_64
0 edi-test-ltr-03:robinhood.d# grep ExecStart /usr/lib/systemd/system/robinhood@.service
ExecStart=**/usr/sbin/robinhood** $RBH_OPT -f /etc/robinhood.d/%I.conf
0 edi-test-ltr-03:robinhood.d#

**Comment by FayeG** [comment]
Here's how i made the rpms
    wget -O/opt/robinhood-3.0.tar.gz 'http://downloads.sourceforge.net/project/robinhood/robinhood/3.0-rc1/robinhood-3.0.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Frobinhood%2Ffiles%2Frobinhood%2F3.0-rc1%2F&ts=1470133658&use_mirror=heanet'
    tar -xzf /opt/robinhood-3.0.tar.gz -C /opt
    cd /opt/robinhood-3.0
    make clean
    ./configure --prefix=/opt/robinhood --enable-lustre
    make rpm

**Comment by tl-cea** [comment]
Indeed, systemd script should be generated taking custom prefix into account.

**Comment by martinetd** [comment]
Pushed an update to gerrit:
https://review.gerrithub.io/288047
