### ISSUE TITLE
RBH 3.0.0.rc1: rbh-config fails when mysql dbs are on separate LVMs

### ISSUE THREAD

**Issue by FayeG** [cea-hpc/robinhood#38]
Some people put each mysql database on a separate LVM mounted under the main mysql data dir, viz:

0 edi-rbh-01:robinhood.d# df | grep mysql | awk '{print $6}'
/var/lib/mysql
/var/lib/mysql/rbh_tools
/var/lib/mysql/rbh_audiodb
/var/lib/mysql/rbh_results
/var/lib/mysql/rbh_scratch

This is done so that one db, which is a file space hog doesn't, damage the others.

However this confuses  rbh-config which complains:
0 edi-rbh-01:robinhood.d#  /opt/robinhood/sbin/rbh-config create_db rbh_audiodb localhost secret bigsecret
...
Configuration summary:
- Database name: 'rbh_audiodb'
- Client hosts: 'localhost'
- Database user name: 'robinhood'

Creating database 'rbh_audiodb'...
mysqladmin: CREATE DATABASE failed; error: 'Can't create database 'rbh_audiodb'; database exists'
Error creating DB.
0 edi-rbh-01:robinhood.d# echo $?
1

Can we have a flag to rbh-config (e.g --db-exists) which stubs out this issue please?

**Comment by tl-cea** [comment]
rbh-config is a wrapper to help for simpler configurations. If you have specific needs, you should directly use mysql/mysqladmin commands to setup your DB.
