### ISSUE TITLE
3.0.0.rc1 user list

### ISSUE THREAD

**Issue by dacron** [cea-hpc/robinhood#40]
When navigating to the user list, selecting a user results in the duplication of table headers, footers, and filter controls. Duplicates are added each time a user is select.

Reproducible on Chrome 52.0.2743.116  and Firefox 43.0.1 (and most likely others).

**Comment by tl-cea** [comment]
web gui is being fully rewritten.
Hopefully an initial version of this rewrite will be proposed in next robinhood update.

**Comment by tl-cea** [comment]
Next web ui will be released with rbh v3.0 rc2.

**Comment by tl-cea** [comment]
Should be fixed in just released 3.0.
