### ISSUE TITLE
3.0.0.rc1 search

### ISSUE THREAD

**Issue by dacron** [cea-hpc/robinhood#41]
The search function in 3.0.0 RC1 results in an invalid SQL statement.

Error is: Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 5000' at line 1.

Database environment is MariaDB 5.5.

**Comment by tl-cea** [comment]
web gui is being fully rewritten.
This should be fixed in the new version.

**Comment by tl-cea** [comment]
Next web ui will be released with rbh v3.0 rc2.

**Comment by tl-cea** [comment]
Should be fixed in just released 3.0.
