### ISSUE TITLE
Web GUI on first time installation dialog box trows error :  Undefined variable: fsname

### ISSUE THREAD

**Issue by arm2arm** [cea-hpc/robinhood#43]
It seems the variable is not initialised.
PHP Notice:  Undefined variable: fsname in /var/www/html/robinhood/app/templates/layoutBlank.php on line 20

**Comment by tl-cea** [comment]
Web UI is being fully rewritten and the new version will be available with the next release (imminent). It is useless testing and reporting issues about the old one.
