### ISSUE TITLE
How to configure http server?

### ISSUE THREAD

**Issue by arm2arm** [cea-hpc/robinhood#44]
Hi, 
Any hints on how to setup apache virtual host?

**Comment by tl-cea** [comment]
New robinhood web UI RPM will come with a virtual host configuration that will be installed in /etc/http.conf.d/

**Comment by arm2arm** [comment]
It does not install anything under CentOS 6.8.

**Comment by tl-cea** [comment]
I mean the web ui your are testing is the old one.
The new version is not even landed to the git repository.
It should be in the next few days.

**Comment by tl-cea** [comment]
The good news is: the new gui just landed in the git repository now (https://github.com/cea-hpc/robinhood/commit/f67f175a86a9cbfcfb2e8d6cdb6b4ee931a7c43f). So you can get it and build the rpm.
The bad new is: it only works with recent php and httpd version (works on el7, but not with versions provided on el6). We still have to work for el6.
