### ISSUE TITLE
sizes page failing with mysql error

### ISSUE THREAD

**Issue by arm2arm** [cea-hpc/robinhood#46]
On top of the sizes.php page an error thrown  with mysql-5.7.15-linux-glibc2.5-x86_64:
`
Error: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'robinhood_lnew.ACCT_STAT.count' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

**Comment by tl-cea** [comment]
This is the old gui.
Patience, the next one has been made compliant with mysql strict modes and tested with mysql-community 5.7.x
