### ISSUE TITLE
wiki: in order to compile rpms smoothly one need to install aclocal and automake as well on Centos 7.2

### ISSUE THREAD

**Issue by arm2arm** [cea-hpc/robinhood#47]
Would be good to update the documentation following:
yum -y install git  autogen  rpm-build autoconf automake gcc libtool glib2-devel libattr-devel  mariadb-devel mailx bison flex
git clone https://github.com/cea-hpc/robinhood.git
cd robinhood
./autogen.sh && ./configure && make -j8 rpm

**Comment by tl-cea** [comment]
Thanks for the advice.
I updated it in "Robinhood v3 admin guide" page. Or were you refering to another documentation?

Also, "make -j8" may not have an impact here as the build is done by rpmbuild, which runs the build step using the "_smp_mflags" rpm macro (%make {?_smp_mflags}).

**Comment by arm2arm** [comment]
Nice!thank you.
