### ISSUE TITLE
CentOS 7 libmysqlclient.so.20 dependency

### ISSUE THREAD

**Issue by jbd** [cea-hpc/robinhood#49]
Hello,

I'm trying to install robinhood-posix using the sourceforge rpm (https://sourceforge.net/projects/robinhood/files/robinhood/3.0-final/RPMS/posix_fs/robinhood-posix-3.0-1.el7.centos.x86_64.rpm/download) on a fresh CentOS 7 installation (and after a yum upgrade) :

```
# yum install robinhood-adm robinhood-posix
Error: Package: robinhood-posix-3.0-1.el7.centos.x86_64 (robinhood)
           Requires: libmysqlclient.so.20(libmysqlclient_20.0)(64bit)
Error: Package: robinhood-posix-3.0-1.el7.centos.x86_64 (robinhood)
           Requires: libmysqlclient.so.20()(64bit)
```

I've got "/usr/lib64/mysql/libmysqlclient.so.18" provided by the installed mariadb-libs-5.5.50-1.el7_2.x86_64 package. Is the .20 version a hard requirement ? This version does not seem to be available :

```
$ yum whatprovides "*libmysqlclient.so.20*"
No matches found
```

I can force install it using some rpm foo (rpm -Uvh --nodeps $(repoquery --location robinhood-posix)), but it does not feel good to me.

**Comment by tl-cea** [comment]
No it's not a hard requirement. We did not take care that we built the RPM on a system with a more recent package. We'll take care of that for the next release.

What you can do to quickly fix that is to rebuild from the SRPM: https://sourceforge.net/projects/robinhood/files/robinhood/3.0-final/SRPMS/robinhood-3.0-1.el7.centos.src.rpm/download

**Comment by jbd** [comment]
Thank you for the suggestion, that's what I did.
