### ISSUE TITLE
rmdir.inc not installed with other include files

### ISSUE THREAD

**Issue by tack0974** [cea-hpc/robinhood#50]
robinhood main package include config examples and includes for compatibility with 2.5 release
example.conf refers to rmdir.inc but this file is not part of install

**Comment by tl-cea** [comment]
True. Thanks for reporting that miss.

Until it is fixed, you can get it from the source repository here:
https://github.com/cea-hpc/robinhood/blob/master/doc/templates/includes/rmdir.inc

**Comment by tl-cea** [comment]
Fix submitted https://review.gerrithub.io/308246
