### ISSUE TITLE
robinhood 3.0 build errors on RHEL 6.6 x86_64: make rpm

### ISSUE THREAD

**Issue by l8gravely** [cea-hpc/robinhood#52]
Trying to build Robinhood 3.0 from tar file to create a RPM to use on RHEL 6.6 x86_64 system.  Regular configure and build works fine, but I wanted to see if doing the rpm build would let me cleanup things more easily after my testing.  I can send the full logs, but the error I get at the end is:

$ make rpm
.
.
.
.

RPM build errors:
    Macro %configure_flags has empty body
    Macro %configure_flags has empty body
    File not found by glob: /var/tmp/robinhood/rpms/BUILDROOT/robinhood-3.0-1.el6.x86_64/usr/lib64/robinhood/librbh_mod_*.so*
make: *** [rpm] Error 1

**Comment by tl-cea** [comment]
These are just warnings:

> Macro %configure_flags has empty body
> Macro %configure_flags has empty body
> 

This is the real issue:

>  File not found by glob: /var/tmp/robinhood/rpms/BUILDROOT/robinhood-3.0-1.el6.x86_64/usr/lib64/robinhood/librbh_mod_.so

But I cannot reproduce this issue.
Something wrong with this line of robinhood.spec ?
> %{_libdir}/robinhood/librbh_mod_*.so*

**Comment by tl-cea** [comment]
Any update ?
