### ISSUE TITLE
Error adding policies

### ISSUE THREAD

**Issue by mkgilbert** [cea-hpc/robinhood#53]
I have a new install of Robinhood on a fairly large Lustre filesystem. We initially did a basic configuration with no policies or file classes just to get robinhood working. We are now starting to try to add policies, but not having any luck getting it to work. I added the following lines to the config file, in an attempt to create a very simple test policy that just sends the output of ls (of all the files of a user called "ricky") to a file:

```
define_policy list_ricky {
     status_manager = basic;
     scope { type == directory and name == 'ricky' }
     default_action = cmd("ls -al >> /tmp/ricky_ls.out");
     default_lru_sort_attr = none;
}

list_ricky_rules {
    rule default {
        condition { creation > 15w }
    }
}
```
After adding that, I did a restart of robinhood and it complained with this message:
```
DB schema change detected: field 'ENTRIES.list_ricky_status' must be added  => Run 'robinhood --alter-db' to apply this change.
```
I ran the command `robinhood --alter-db`, which took about 7 or 8 minutes to finish, but it failed with the following errors:
```
2017/01/03 10:54:28 [38147/1] ListMgr | table ACCT_STAT does not exist (or wrong version): creating it.
2017/01/03 10:54:28 [38147/1] ListMgr | Populating accounting table from existing DB contents. This can take a while... (estim. duration: ~6.4min)
2017/01/03 11:05:19 [38147/1] ListMgr | Unhandled error 1030: default conversion to DB_REQUEST_FAILED
2017/01/03 11:05:19 [38147/1] ListMgr | Error 7 executing query 'INSERT INTO ACCT_STAT(uid,gid,type,list_ricky_status,size,blocks, count,sz0,sz1,sz32,sz1K,sz32K,sz1M,sz32M,sz1G,sz32G,sz1T) SELECT uid,gid,type,list_ricky_status,SUM(size),SUM(blocks),COUNT(id),SUM(size=0),SUM(sz_range(size)=0),SUM(sz_range(size)=1),SUM(sz_range(size)=2),SUM(sz_range(size)=3),SUM(sz_range(size)=4),SUM(sz_range(size)=5),SUM(sz_range(size)=6),SUM(sz_range(size)=7),SUM(sz_range(size)>=8) FROM ENTRIES  GROUP BY uid,gid,type,list_ricky_status': Got error -1 from storage engine
2017/01/03 11:05:19 [38147/1] ListMgr | Failed to populate accounting table: Error: Got error -1 from storage engine
2017/01/03 11:05:19 [38147/1] Main | Error initializing list manager: request error (7)
```

do I need to change the scope to "all"? I'm not sure exactly what to do here. Thank you for any help!

**Comment by tl-cea** [comment]
Replied on robinhood-support

**Comment by mkgilbert** [comment]
I resolved my issue, which was a MySQL configuration problem. It had to do with the `innodb_force_recovery` setting, which I had on and set to 4. Taking this out, restarting mysql and dropping and rebuilding the robinhood database solved it.
