### ISSUE TITLE
expected db size?

### ISSUE THREAD

**Issue by mkgilbert** [cea-hpc/robinhood#54]
Is there some kind of metric or best guess for approximately how much room the robinhood mysql databases will need once a full scan is complete? We have a 161TB lustre system and the initial scan keeps filling up our volume. The highest it has been so far is 10GB but we keep having to increase the size of our volume because mysql keeps locking up due to no space left.

Is there some way to know how much space we will require?

**Comment by tl-cea** [comment]
The usual DB size is around 1k per entry in your FS.
