### ISSUE TITLE
Feature: Improve the search function for files on the web GUI

### ISSUE THREAD

**Issue by gabrieleiannetti** [cea-hpc/robinhood#58]
Dear all,

currently Robinhood supports displaying the first n files (default: 1000) queried from 
the MySQL database for a user/group.

We would like to ask you the following questions:

1. Is there a plan about adding a more precise 'file search' function in the web GUI e.g. for filtering by sizes, last modified time, a specific name or pattern...etc.?

2. What do you think about a paging mechanism (e.g. in PHP) for iterating over large file sets queried from the database?

Best regards,
    Gabriele

**Comment by ja-cea** [comment]
Hi,

I've just submitted some of the changes in the following patch:
(https://review.gerrithub.io/#/c/346805/1)

You can also specify a pattern using % as a wildcard and _ for matching one carac. in UID, GUID and Filename fields.

Regards,

Jérôme

**Comment by gabrieleiannetti** [comment]
Hello Jérôme,

thanks, good to know!

Regards
Gabriele
