### ISSUE TITLE
Robinhood v3: Optimization too agressive

### ISSUE THREAD

**Issue by geraldhofer** [cea-hpc/robinhood#64]
I am copying some files with tar into the Lustre file system. Some files get archived as expected, but most files stay "new".

My condition is just based on the modification time:

        condition { last_mod >= 1min }

An example file that stays "new":

```
[root@tclin01 ~]# rbh-report --entry-info /gdatat1/siteB/root/usr/share/locale/pt/LC_MESSAGES/psmisc.mo
Using config file '/etc/robinhood.d/gdatat1.conf'.                                                                                                                     
id             :        [0x200001b71:0x7088:0x0]                                                                                                                       
parent_id      :        [0x200001b71:0x7076:0x0]                                                                                                                       
name           :        psmisc.mo
path updt      :        2017/02/19 07:52:23
path           :        /gdatat1/siteB/root/usr/share/locale/pt/LC_MESSAGES/psmisc.mo
depth          :        7
user           :        root
group          :        root
size           :        752
spc_used       :        512
creation       :        2017/02/19 07:52:18
last_access    :        2017/02/19 07:52:18
last_mod       :        2014/10/10 03:53:32
last_mdchange  :        2017/02/19 07:52:18
type           :        file
mode           :        rw-r--r--
nlink          :        1
md updt        :        2017/02/19 07:52:23
fileclass      :        small_files+siteB
class updt     :        2017/02/19 07:52:23
stripe_cnt, stripe_size,      pool:              1,     1.00 MB,         
stripes        :        ost#2: 35124
lhsm.status    :        new
lhsm.archive_id:        0
lhsm.no_release:        no
lhsm.no_archive:        no
lhsm.last_archive:      0
lhsm.last_restore:      0
alert.last_check:       0
alert.last_alert:       0

```
It looks like the optimization is just too aggressive:

```
2017/02/19 08:47:04 [25442/2] lhsm_archive | Checking policy rules for all
2017/02/19 08:47:04 [25442/2] lhsm_archive | Building policy list - last full FS Scan: 2017/02/17 19:07:22
2017/02/19 08:47:04 [25442/2] lhsm_archive | Starting policy run
2017/02/19 08:47:04 [25442/2] lhsm_archive | Optimization: considering entries with last_mod newer than 2017/02/17 19:16:36
2017/02/19 08:47:04 [25442/2] lhsm_archive | Policy run summary: time=01s; target=all; 0 successful actions (0.00/sec); volume: 0 (0/sec); 0 entries skipped; 0 errors.

```
So it looks like it is possible that user level tools reset the modification time past the time of the optimization and robinhood is not aware of it.

As soon as I restart robinhood or manually run the policy the optimization does not apply and the file gets archived as expected.

**Comment by geraldhofer** [comment]
I think a workaround is to use following condition:
`condition { last_mod >= 1min or creation >= 1min }`

**Comment by tl-cea** [comment]
Hello,
Indeed. By default, robinhood optimizes its policy runs the following way if your policies are only based on the "lru_sort_attr" of the policy (mtime in your case): if it as already processed all entries having mtime (last_mod) up to X, next time it only considers entries having mtime > X. Of course, it is not relevant if file mtimes are cheated (i.e. created with mtime in the past).
This optimization is disabled if you specify "none" as lru_sort_attr in <policy>_parameters:
"lru_sort_attr = none"
This results in faster policy runs, but the order of policy application is kind of random.
If you still want a time ordering of policy actions, you can also try "lru_sort_attr = creation". Creation time cannot be faked as mtime, so the optimization won't skip entries in that case.
