### ISSUE TITLE
Robinhood v3: not all file class definitions are used for action_params

### ISSUE THREAD

**Issue by geraldhofer** [cea-hpc/robinhood#65]
I am testing a configuration that should sort files into different archive ids based on location and I want to use a different parameters for the copytool based on file size. But I think I ran into a bug in that configuration.

My understanding is that the parameters should be done based on the following order:

1) As default parameters for a policy
2) In policy triggers
3) In policy rules
4) In fileclass definitions

So these are the different levels in my example:

1) The parameters sections has a default and defines the command:

```
lhsm_archive_parameters {
    nb_threads = 8;
## archive 1000 files max at once
#    max_action_count = 1000;
#    max_action_volume = 1TB;

    # suspend policy run if action error rate > 50% (after 100 errors)
    suspend_error_pct = 50%;
    suspend_error_min= 100;

    # overrides policy default action
    action = cmd("lfs hsm_archive --archive {archive_id} --data {data} /gdatat1/.lustre/fid/{fid}");

    # default action parameters
    action_params {
        archive_id = 1;
        data = t2;
    }
}

```
2) No action params in the trigger:

```
lhsm_archive_trigger {
    trigger_on = periodic;
    check_interval = 1min;
}
```

3) The rules section has currently no parameters either ( I had the archive ids on that level earlier):

```
lhsm_archive_rules {
    ignore_fileclass = empty_files;
    ignore_fileclass = no_archive;



    rule archive_siteA {
        target_fileclass = siteA;

        condition { last_mod >= 1min }
#        action_params { archive_id = 1;
#                       data = "t1";
#       }
    }

    rule archive_siteB {
        target_fileclass = siteB;

        condition { last_mod >= 1min }
#        action_params { archive_id = 2; }
    }

    rule archive_siteAB {
        target_fileclass = siteAB;

        condition { last_mod >= 1min }
#        action_params { archive_id = 3; }
    }


    # fallback rule
    rule default {
        action_params { archive_id = 1; }
        condition { last_mod >= 1min }

    }
}
```

4) The file class definitions have now the different parameters:

```
FileClass empty_files {
    definition { type == file and size == 0 }
    lhsm_archive_action_params { data = "t1"; }
    # report = yes (default)
}
FileClass small_files {
    definition { type == file and size > 0 and size <= 16MB }
    lhsm_archive_action_params { data = "t1"; }
    # report = yes (default)
}
FileClass std_files {
    definition { type == file and size > 16MB and size <= 1GB }
    lhsm_archive_action_params { data = "t2"; }
}
FileClass big_files {
    definition { type == file and size > 1GB }
    lhsm_archive_action_params { data = "t2"; }
}
FileClass largedir {
    definition { type == directory and dircount > 10000 }
}
FileClass siteA {
    definition { tree == "/gdatat1/siteA" }
    lhsm_archive_action_params { archive_id = 1; }
}
FileClass siteB {
    definition { tree == "/gdatat1/siteB" }
    lhsm_archive_action_params { archive_id = 2;
                                 data = "t1"; }
}
FileClass siteAB {
    definition { tree == "/gdatat1/siteAB" }
    lhsm_archive_action_params { archive_id = 3; }
}
FileClass no_archive {
    definition { tree == "/gdatat1/no_archive" }
}
```

The observation is that FileClass definitions small_files, std_files and big_files does not seem to set the {data} parameter.
This particular configurations does test that the {data} parameter in principal gets set in a FileClass. If I write a file into /gdatat1/siteB the file gets migrated to archive_id 2 and data "t1". So both parameters are overwritten from the default archive_id 1 and "t2".
But if I am writing a small file into /gdatat1/siteAB the {data} parameter does not get overwritten from the default by the small_files FileClass.

```
2017/02/17 18:18:58 [2499/4] lhsm_archive | Checking if entry /gdatat1/siteAB/test/resolv.conf matches policy rules
2017/02/17 18:18:58 [2499/11] lhsm_archive | End of list (1 entries returned)
2017/02/17 18:18:58 [2499/11] lhsm_archive | Waiting for the end of current pass: still 1 entries pending (0 in queue, 1 being processed). Last action 0s ago.
2017/02/17 18:18:58 [2499/4] lhsm_archive | Considering entry [0x200001b70:0x14d:0x0]
2017/02/17 18:18:58 [2499/4] Policy | Matching 'no_archive': rc=0
2017/02/17 18:18:58 [2499/4] Policy | Entry [0x200001b70:0x14d:0x0] matches target file class 'siteAB' of policy 'archive_siteAB'
2017/02/17 18:18:58 [2499/4] lhsm_archive | Entry /gdatat1/siteAB/test/resolv.conf matches the condition for policy rule 'archive_siteAB'.
2017/02/17 18:18:58 [2499/4] params | 't2'->'t2' in parameter data='t2'
2017/02/17 18:18:58 [2499/4] params | '3'->'3' in parameter archive_id='3'
2017/02/17 18:18:58 [2499/4] lhsm_archive | Executing policy action on: 0x200001b70:0x14d:0x0 (/gdatat1/siteAB/test/resolv.conf)
2017/02/17 18:18:58 [2499/4] lhsm_archive | [0x200001b70:0x14d:0x0]: action_params: data=t2, archive_id=3
2017/02/17 18:18:58 [2499/4] params | 'lfs'->'lfs' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | [0] 'lfs'->'lfs' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | 'hsm_archive'->'hsm_archive' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | [1] 'hsm_archive'->'hsm_archive' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | '--archive'->'--archive' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | [2] '--archive'->'--archive' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | '{archive_id}'->'3' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | [3] '{archive_id}'->'3' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | '--data'->'--data' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | [4] '--data'->'--data' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | '{data}'->'t2' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | [5] '{data}'->'t2' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | '/gdatat1/.lustre/fid/{fid}'->'/gdatat1/.lustre/fid/0x200001b70:0x14d:0x0' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] params | [6] '/gdatat1/.lustre/fid/{fid}'->'/gdatat1/.lustre/fid/0x200001b70:0x14d:0x0' in action command 'lfs'
2017/02/17 18:18:58 [2499/4] lhsm_archive | [0x200001b70:0x14d:0x0]: action: cmd(lfs hsm_archive --archive 3 --data t2 /gdatat1/.lustre/fid/0x200001b70:0x14d:0x0)
2017/02/17 18:18:58 [2499/4] ExecCmd | Spawning external command "lfs"
2017/02/17 18:18:58 [2499/4] ExecCmd | Child 2512 terminated with 0
2017/02/17 18:18:58 [2499/4] lhsm_archive | lhsm_archive success for '/gdatat1/siteAB/test/resolv.conf', matching rule 'archive_siteAB' (fileset=siteAB), last_mod 9.5mi
n ago, size=71
```

I did also test a config where I did not set a default and I saw that the {data} parameter was not set at all and the lfs hsm_archive produced an error.

**Comment by tl-cea** [comment]
Only the matched "target_fileclass" is taken into account for action_params inheritance.

**Comment by geraldhofer** [comment]
Given your answer: Does it makes sense to change that from a bug to a RFE?

Currently that inheritance seems to be mainly there because of syntax reasons? Basically on what level you define the variables, as part of a rule or as part of the fileclass.

The current implementation seems to allow only one match for the target_fileclass. I have experimented a bit and found no way to match multiple file classes at the same time for a rule. If I can match against multiple file classes at the same time (fileclass1 AND fileclass2) then I would be be able to inherit multiple independent variables from the file classes. But if I only ever can match one fileclass in a rule then there is no need to have variables in the file classes at all - I can always set that in the rules section. It certainly was not clear from the documentation available that this limitation exists.

So the only way to implement my requirement would be to have a fileclass for every combination of the file classes. 

So currenty I have as independent file classes:
siteA archive_id=1
siteB archive_id=2
site_AB archive_id=3

small files=t1
large files=t2

So I need to to now set up 6 file classes - and 6 rules.
siteA_small 
siteA_large
siteB_small
siteB large
siteAB_small
siteAB_large

Then I can set the appropriate variables in the rules (or the fileclass).

The issue for the intended use is that the actual implementation will use a lot of different projects, each will have one of the three archive_id's. So to add a new project I need to add two file classes and add them into the rules. If I later want to change the cutoff between the small and large files to change the behavior I need to change all the rules in each project, instead of only one fileclass rule.

So using the non overlapping file classes for reporting is very useful - but the current limitations of the rule and the inheritance, don't allow the same flexibility with rules. Maybe you can consider that as a future enhancement.
