### ISSUE TITLE
lhsm_remove ignores rm_time query option during DB select phase

### ISSUE THREAD

**Issue by tack0974** [cea-hpc/robinhood#72]
lhsm_remove process, removing entries with grace period expired from SOFT_RM table, does not
use rm_time parameter during select process.
during query build process rm_time query filter is dropped by "append_simple_expr" at
listmgr_filters.c:485 "if (readonly_fields(tmp))"; apparently rm_time is considered a RO field in DB, because ATTR_INDEX_rm_time matches FUNC_ATTR in rbh_types.h.
Using rm_time filter at DB query time could save a lot of processing time when soft_rm table contains a lot of entries.

**Comment by tack0974** [comment]
Current query (from debug full)
SELECT id,fullpath,uid,gid,size,blocks,last_access,last_mod,last_mdchange,type,mode,nlink,rm_time,lhsm_status,lhsm_archid,lhsm_uuid FROM SOFT_RM WHERE (type='file' OR type IS NULL) ORDER BY rm_time ASC

how it should be: (comment "return 0" at line 487)
SELECT id,fullpath,uid,gid,size,blocks,last_access,last_mod,last_mdchange,type,mode,nlink,rm_time,lhsm_status,lhsm_archid,lhsm_uuid FROM SOFT_RM WHERE (type='file' OR type IS NULL) AND (rm_time<1483710569 OR rm_time IS NULL) ORDER BY rm_time ASC

**Comment by tl-cea** [comment]
> comment "return 0" at line 487

Do you remember in what file?

**Comment by tack0974** [comment]
sure, it's  listmgr_filters.c

**Comment by tl-cea** [comment]
OK. Thanks. I have to figure out why we did remove read only fields from criteria, and if there are side effects when removing this line.

**Comment by tack0974** [comment]
commenting "return 0" may break rmdir_recursive functionality

**Comment by tack0974** [comment]
Fix has landed with commit c2483c8
Change-Id: I7132d023a7e484b2694ddaea052016fa34cb5ad4
