### ISSUE TITLE
What does "time_crit" mean?

### ISSUE THREAD

**Issue by pol** [cea-hpc/robinhood#75]
For rbh-find, the documentation for the value given to -ctime, -mtime, etc is "time_crit", with the format of `[-|+]<val>[s|m|h|d|y]`.   But what is the point of reference?  If I search for `-ctime -90d`, does that mean "a file created between now and 90 days ago"?  If so, what does `-ctime +90d` mean?  Presumably it's not that the file was created in the future... does it use the first instance of -ctime to establish a reference point (an upper or lower bound), and then the second is the other bound (with a default of "now")?

**Comment by tl-cea** [comment]
It is the same as "find" command.
"-ctime -90d" matches files with a ctime more recent than 90 days => in [now-90d ; now]
"-ctime +90d" matches files with a ctime older than 90d (between ]-inf ; now -90d]).
Notice that ctime is not creation time, it is POSIX ctime (time of last metadata change).
In rbh-find, creation time is designated as "-crtime"
