### ISSUE TITLE
hsm archive request for FIDs that are missing in Lustre cause infinite loop

### ISSUE THREAD

**Issue by geraldhofer** [cea-hpc/robinhood#77]
I was debugging a issue where several files were in the Robinhood database that were missing in the Lustre file system. The migration task picked them up and tried to schedule migrations. It was skipping over these missing files:

`2017/04/27 12:22:16 [24376/23] Migr | stat() failed on /lustre/.lustre/fid/[0x200002b1a:0x1fb5:0x0]. Skipping it.`

But it eventually re-queued these request and got stuck in an infinite loop:

`2017/04/27 16:16:40 [15265/3] Migr | 3091 migration finished / 3091 total`
`2017/04/27 16:16:40 [15265/3] Migr | Starting migration`

The result was that no files were actually migrated.
The obvious fix is to scan the full file system and get rid of these entries. But I think Robinhood could deal with that situation better.

That was on Robinhood 2.5. not sure if the behavior would be different in Robinhood 3.0.

**Comment by tl-cea** [comment]
There is a patch to fix that in robinhood v3: https://review.gerrithub.io/#/c/356171/

Similarly, this should be fixed in v2 by applying this patch:

```
diff --git a/src/policy_modules/migration/migr_arch.c b/src/policy_modules/migration/migr_arch.c
index 64c8f59..883dc2c 100644
--- a/src/policy_modules/migration/migr_arch.c
+++ b/src/policy_modules/migration/migr_arch.c
@@ -1149,10 +1149,10 @@ static int check_entry( lmgr_t * lmgr, migr_item_t * p_item, attr_set_t * new_at
                     fid_path );
 
         /* This entry has been processed and has probably removed */
-        if ( rc == ENOENT )
-            /** @TODO remove entry from DB if errno = ENOENT ? */
+        if (rc == ENOENT) {
+            invalidate_entry(lmgr, &p_item->entry_id);
             return MIGR_ENTRY_MOVED;
-        else
+        } else
             return MIGR_STAT_FAILURE;
     }
 
```

**Comment by tl-cea** [comment]
Did it fix your problem?

**Comment by geraldhofer** [comment]
I fixed it manually in the Robinhood database by removing the entries in question. I was able to extract a list with candidates out of the log file. So I have not verified that particular patch. Luckily we have not seen that problem again.
