### ISSUE TITLE
autodetect and use Lustre when building

### ISSUE THREAD

**Issue by brianjmurrell** [cea-hpc/robinhood#78]
It would be nice if RH's configure could detect the presence of the needed Lustre headers files and use them if found, without being pointed at them.

Granted, while this would be easier and nicer if there were a [lustre-devel package](https://jira.hpdd.intel.com/browse/LU-9215), however this can still be achieved using the lustre-client RPM.  It contains the necessary headers.

I can do the following for example (after unpacking and `cd`ing into the RH source directory) to build RH with Lustre support:

```
rm -fr lustre
mkdir -p lustre/lustre/include
ln -s /usr/include/lustre lustre/lustre/include/lustre
ln -s /usr/include/linux lustre/lustre/include/linux
ln -s /usr/lib64 lustre/lustre/utils
./autogen.sh
./configure  --with-purpose=LUSTRE_HSM --with-lustre=$(pwd)/lustre
make -j 8 || make
```

But really, the symlinks and the `--with-lustre=...` shouldn't actually be necessary since the include and utils will be in a known location.

**Comment by qb-cea** [comment]
@tl-cea will have to confirm, but I think this feature is already implemented (documentation doesn't report needing the `--with-purpose` or `--with-lustre` option at configure time).

**Comment by tl-cea** [comment]
--with-lustre is only when you have lustre in a different location than the standard one (eg. if you have a lustre build tree in your home directory...).
If you don't specify it, it looks then in the standard location where they are installed by the lustre RPMs i.e. /usr/include/lustre/

**Comment by brianjmurrell** [comment]
Interesting.  I should have tried it without before filing the ticket.  So I did remove the symlinking and it does seem to have acknowledged the presence of Lustre.  Some checks failed though:

```
checking for llapi_obd_statfs in -llustreapi... yes
checking lustre/lustreapi.h usability... yes
checking lustre/lustreapi.h presence... yes
checking for lustre/lustreapi.h... yes
checking lustre/lustre_idl.h usability... no
checking lustre/lustre_idl.h presence... no
checking for lustre/lustre_idl.h... no
checking Lustre source version... grep: /builddir/build/BUILD/robinhood-2.5.5/lustre/config.h: No such file or directory
none installed
checking for llapi_msg_set_level in -llustreapi... yes
checking for struct obd_statfs... yes
checking for llapi_fid2path in -llustreapi... yes
checking for llapi_fd2fid in -llustreapi... yes
checking for llapi_file_fget_mdtidx in -llustreapi... yes
checking for llapi_changelog_start in -llustreapi... yes
checking whether CL_IOCTL is declared... no
checking whether CL_LAYOUT is declared... yes
checking whether CLF_RENAME is declared... yes
checking for llapi_fswap_layouts in -llustreapi... yes
checking llapi-fork-support option... disabled
checking mds-stat option... disabled
checking for llapi_get_poollist in -llustreapi... yes
checking for llapi_get_poolmembers in -llustreapi... yes
checking for struct lov_user_ost_data_v1.l_object_seq... no
checking for struct lov_user_ost_data_v1.l_object_id... no
```

Will any of those impair the Lustre/HSM functionality of RH?

**Comment by tl-cea** [comment]
> checking Lustre source version... grep: /builddir/build/BUILD/robinhood-2.5.5/lustre/config.h: No such file or directory
> none installed

You should only see those lines if you specifed "--with lustre" which is not needed if lustre is installed in the usual path.

Anyhow, it looks robinhood has correctly detected the liblustreapi, so the Lustre/HSM functionality won't be affected.

**Comment by brianjmurrell** [comment]
> You should only see those lines if you specifed "--with lustre" which is not needed if lustre is installed in the usual path.

Oops.  You are right.  I removed the symlinking hack but forgot to remove the `configure` option.  With it removed a few of the failed checks go away:

```
$ ./configure --with-purpose=LUSTRE_HSM --mandir=/usr/share/man --libdir=/usr/lib64
...
checking for llapi_obd_statfs in -llustreapi... yes
checking lustre/lustreapi.h usability... yes
checking lustre/lustreapi.h presence... yes
checking for lustre/lustreapi.h... yes
checking lustre/lustre_idl.h usability... no
checking lustre/lustre_idl.h presence... no
checking for lustre/lustre_idl.h... no
checking Lustre version... none installed
checking for llapi_msg_set_level in -llustreapi... yes
checking for struct obd_statfs... yes
checking for llapi_fid2path in -llustreapi... yes
checking for llapi_fd2fid in -llustreapi... yes
checking for llapi_file_fget_mdtidx in -llustreapi... yes
checking for llapi_changelog_start in -llustreapi... yes
checking whether CL_IOCTL is declared... no
checking whether CL_LAYOUT is declared... yes
checking whether CLF_RENAME is declared... yes
checking for llapi_fswap_layouts in -llustreapi... yes
checking llapi-fork-support option... disabled
checking mds-stat option... disabled
checking for llapi_get_poollist in -llustreapi... yes
checking for llapi_get_poolmembers in -llustreapi... yes
checking for struct lov_user_ost_data_v1.l_object_seq... no
checking for struct lov_user_ost_data_v1.l_object_id... no
```

> Anyhow, it looks robinhood has correctly detected the liblustreapi, so the Lustre/HSM functionality won't be affected.

Excellent.  Thanks for the feedback.
