### ISSUE TITLE
Cleanup does not check for archive flag

### ISSUE THREAD

**Issue by dtcray** [cea-hpc/robinhood#79]
Cleanup process does not check hsm_status of file, archive files removed by cleanup leave orphans in HSM backend.
Cleanup should either send hsm_remove request or put entry in SOFT_RM table if a file has archive flags set

**Comment by tl-cea** [comment]
When the cleanup policy deletes a file, this raises an UNLINK changelog record whose flags indicates the file was archived. When processing this changelog, robinhood will add a record in SOFTRM for this entry so it can be deleted from the backend.
Do you state a different behavior?

However, I admit it only works if robinhood is feeded by changelogs (not scan).
For other cases, the fix should be: "ListMgr_Remove" operation should be replaced by a "ListMgr_SoftRemove" in policy_run.c if the entry is eligible for soft rm for any of the defined policies.

**Comment by dtcray** [comment]
but when RH processes unlink event all entries related to the file are gone especially UUID (tested using custom uuid : trusted.custom.uud)

**Comment by tl-cea** [comment]
Right.
Based on the example of rm_record() in std_pipeline.c, we should move entries to SOFTRM in some cases during the policy run, instead of calling ListMgr_Remove:
> if (has_deletion_policy()) {
>     pa = match_all_softrm_filters(id, attrs);
>     switch (pa) {
>     ...

**Comment by dtcray** [comment]
what if unlink policy does unlink file and invalidate DB entry and let Changelog and/or Scan+Garbage collection deal with DB entry removal ?

**Comment by tack0974** [comment]
option to disable DB entries removal on tmpfs_cleanup introduced with commit
b96fb81b8f227bd4fc408c8edd2ac4a368b3d0bd
(to enable set invalidate_dbentry = true in cleanup parameters);
