### ISSUE TITLE
attribute is missing for checking fileset for all fileclasses

### ISSUE THREAD

**Issue by bp85** [cea-hpc/robinhood#94]
Hi,
we're using robinhood-3.1.1 with lustre 2.8 
we've defined fileclasses as below
```
fileclass largedir {
    definition { type == directory and dircount > 30000 }
}
fileclass rc_files {
    Definition { tree == "/n/scratch2/rc" }
}
```
when running policies we're seeing multiple errors like 
```
Policy | [0x20003217c:0x1b06c:0x0]: attribute is missing for checking fileset 'rc_files'
Policy | [0x200000bd0:0x3:0x0]: attribute is missing for checking fileset 'largedir'
```
This is very annoying and we can't use fileclass definitions to run policies

Any help would be appreciated

**Comment by dnhodgson** [comment]
Can you do a `rbh-report -e <fid>` on one of the IDs that it's throwing an error for? Also look at one that it doesn't error for and see if there is a difference...

**Comment by dnhodgson** [comment]
can you select everything from the NAMES and ENTRIES tables about the missing ID? Maybe see what's in the database about this file?  You can also try to see if `rbh-find 0x200032291:0x1231e:0x0` gets you anything.  It should return the file path.

When was the last time a full scan was done? Maybe the database is out of sync with the filesystem?

**Comment by bp85** [comment]
DB return emptyset from both tables and rbh-find says no such file or parameter
The last FS-Scan was done this morning, so DB isn't out of date.
Dumb question is, if a file is deleted when policy is trying to apply on that file what happens?
I mean if a file is trying to match for a fileclass and it's deleted, what error it produce?
