### ISSUE TITLE
hsm_remove select statement always have ORDER BY

### ISSUE THREAD

**Issue by dtcray** [cea-hpc/robinhood#98]
Just discovered that SELECT statement for hsm_remove always have "ORDER BY rm_time" at the end of select statement no matter what is set in lru_sort_attr (in lhsm_remove_parameters) and default_lru_sort_attr in policy definition
can anybody point me to the code responsible for this ?

**Comment by dtcray** [comment]
code found: listmgr_remove.c line 881
 if (p_sort_type == NULL || p_sort_type->order == SORT_NONE)
if sort is NONE or not defined add default sort, this could be pretty bad for crowded SOFT_RM table

**Comment by tl-cea** [comment]
Fixed in 3.1.5
